name: Test

on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"

      - name: touch file
        run: touch hola.txt

      - name: Set text
        run: echo "Hola Mundo" >> hola.txt

      - name: Read file
        run: cat hola.txt

  other:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v2

    - name: LS
      run: ls -al

    - name : Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: latest

    - name: node version
      run: node -v

    #- name: ls
    #  run: |
    #    chmod +x script.sh
    #    ./script.sh