name: Ejemplo de Composite Action

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: example
          
    steps:
      - name: Test
        uses: ls